[package]
name = "git-rust"
version = "0.1.0"
authors = ["Riley Rice"]
edition = "2024"
rust-version = "1.85"

[dependencies]
anyhow = "1.0.68"
bytes = "1.3.0"
clap = { version = "4.5.32", features = ["derive"] }
flate2 = "1.0.34"
sha1 = "0.10.6"
thiserror = "1.0.38"
